export const products = [
  {
    id: 1,
    name: 'Laptop Gamer',
    description: 'Potente laptop para gaming con GPU dedicada.',
    stock: 15,
    price: 1500,
  },
  {
    id: 2,
    name: 'Smartphone 5G',
    description: 'Teléfono de última generación con conectividad 5G.',
    stock: 30,
    price: 800,
  },
  {
    id: 3,
    name: 'Auriculares Inalámbricos',
    description: 'Auriculares Bluetooth con cancelación de ruido.',
    stock: 50,
    price: 120,
  },
  {
    id: 4,
    name: 'Monitor 4K',
    description: 'Pantalla UHD de 27 pulgadas con alta fidelidad de color.',
    stock: 20,
    price: 400,
  },
  {
    id: 5,
    name: 'Teclado Mecánico',
    description: 'Teclado RGB con switches mecánicos para gamers.',
    stock: 40,
    price: 100,
  },
  {
    id: 6,
    name: 'Mouse Gamer',
    description: 'Ratón ergonómico con sensor de alta precisión.',
    stock: 35,
    price: 60,
  },
  {
    id: 7,
    name: 'Silla Ergonómica',
    description: 'Silla cómoda con soporte lumbar para largas sesiones.',
    stock: 10,
    price: 250,
  },
  {
    id: 8,
    name: 'Disco SSD 1TB',
    description: 'Almacenamiento rápido con tecnología NVMe.',
    stock: 25,
    price: 150,
  },
  {
    id: 9,
    name: 'Impresora Multifunción',
    description: 'Impresora con escáner y conexión Wi-Fi.',
    stock: 12,
    price: 220,
  },
  {
    id: 10,
    name: 'Tableta Gráfica',
    description: 'Tableta para diseño digital con lápiz sensible a presión.',
    stock: 18,
    price: 300,
  },
]
